sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:slug_title/
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }